### PR TITLE
Minor change to use the variables

### PR DESCRIPTION
**Pull request by TheRepSter**
Replaced `{'User-Agent': 'Mozilla/5.0'})` with the variable header that contained the same dictionary

### CODE REVIEW

**Comment by boobfuck** [comment]
Hey there,

First of all, thanks for contributing! But I fail to see what this PR accomplishes. The user-agent is defined in a variable `headers` in line 86 because this user-agent is being used in line 87 and 104. Why remove this variable in line 104 and explicitly define the user-agent?

**Comment by TheRepSter** [comment]
In line 104 it's not being used, the PR is to use that variable

**Comment by boobfuck** [comment]
E0EC192D-14AB-4D26-A821-123308B4B5D3

I think you're misunderstanding what I meant here. Whether I merge this PR or not, it still is the same thing.

**Comment by boobfuck** [comment]
Oops sorry, I was confused. Thanks.

**Pull request merged**
